FROM jenkins/jenkins

# Installer les dépendances nécessaires pour Docker
USER root
RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce && \
    rm -rf /var/lib/apt/lists/*

# Désactiver le réglage des ulimits dans le script d'init Docker
RUN sed -i 's/ulimit -Hn/# ulimit -Hn/g' /etc/init.d/docker

# Revenir à l'utilisateur jenkins
USER jenkins
